//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepthFirst<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public String output = "";
   public int ga = -1;
   public int na = -1;
   public boolean poss(String off)
   {
       int m = (ga>na) ? ga : na;
       m = m*4;
       int offset = Integer.parseInt(off);
       return offset>=0 && offset<m && offset % 4 ==0;
   }
   public int findoff(int off)
   {
       if (ga>0 && na==0 && !poss(String.valueOf(off)))
           off -= ga*4;
       else if (ga==0 && na>0)
                off += na*4;
    return off;
   }
  
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    * f13 -> ( Procedure() )*
    * f14 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      output += "\t.text\n";
      output += "\t.globl main\n";
      output += "main:\n";
      String g = (String)n.f2.accept(this, argu);
      ga = Integer.parseInt(g);
      ga = (ga>=4)? (ga-4):0;
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      String size = (String)n.f5.accept(this, argu);
      int s = Integer.parseInt(size);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      String ma = (String)n.f8.accept(this, argu);
      int m = Integer.parseInt(ma);
      m = (m>=4)? (m-4) : 0;
      na = m;
      size = String.valueOf((s+m)*4+4);
      n.f9.accept(this, argu);

      output += "\tmove $fp, $sp\n";
      output += "\tsw $ra, -4($fp)\n";
      output += "\tsubu $sp, $sp, "+size+"\n";
      
      n.f10.accept(this, argu);

      output += "\taddu $sp, $sp, "+size+"\n";
      output += "\tlw $ra, -4($fp)\n";
      output += "\tj $ra\n\n";

      n.f11.accept(this, argu);
      ga = -1;
      na = -1;
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      n.f14.accept(this, argu);
      output += "\t.text\n";
      output += "\t.globl _halloc\n";
      output += "_halloc:\n";
      output += "\tli $v0, 9\n";
      output += "\tsyscall\n";
      output += "\tj $ra\n\n";

      output += "\t.text\n";
      output += "\t.globl _print\n";
      output += "_print:\n";
      output += "\tli $v0, 1\n";
      output += "\tsyscall\n";
      output += "\tla $a0, newl\n";
      output += "\tli $v0, 4\n";
      output += "\tsyscall\n";
      output += "\tj $ra\n\n";

      output += "\t.data\n";
      output += "\t.align 0\n";
      output += "newl:\t.asciiz \"\\n\"\n";

      System.out.println(output);
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      R _ret=null;
      if(n.f0.present())
      { 
          for(Enumeration<Node> e = n.f0.elements(); e.hasMoreElements(); )
          { 
              Node node = e.nextElement();
              NodeSequence seq = (NodeSequence)node;
              NodeOptional maybelabel = (NodeOptional)seq.elementAt(0);
              if(maybelabel.present())maybelabel.node.accept(this,(A)"NOW");
              seq.elementAt(1).accept(this, argu);
          }
      }
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    */
   public R visit(Procedure n, A argu) {
      R _ret=null;
      String name = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String g =(String)n.f2.accept(this, argu);
      ga = Integer.parseInt(g);
      ga = (ga>=4)? (ga-4):0;
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      String size = (String)n.f5.accept(this, argu);
      int s = Integer.parseInt(size);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      String ma = (String)n.f8.accept(this, argu);
      int m = Integer.parseInt(ma);
      na = (m>=4)? (m-4):0;
      size = String.valueOf((s-ga+na)*4+8);
      n.f9.accept(this, argu);

      output += "\t.text\n";
      output += "\t.globl "+name+"\n";
      output += name+":\n";
      output += "\tsw $fp, -8($sp)\n";
      output += "\tmove $fp, $sp\n";
      output += "\tsw $ra, -4($fp)\n";
      output += "\tsubu $sp, $sp, "+size+"\n";

      n.f10.accept(this, argu);

      output += "\taddu $sp, $sp, "+size+"\n";
      output += "\tlw $ra, -4($fp)\n";
      output += "\tlw $fp, -8($sp)\n";
      output += "\tj $ra\n\n";
      n.f11.accept(this, argu);
      ga = -1;
      na = -1;
      n.f12.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    *       | ALoadStmt()
    *       | AStoreStmt()
    *       | PassArgStmt()
    *       | CallStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      output += "\tnop\n";
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      // output += "\terror\n";
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Reg()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String r = (String)n.f1.accept(this, argu);
      String lab = (String)n.f2.accept(this, argu);
      output += "\tbeqz "+r+" "+lab+"\n";
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String lab = (String)n.f1.accept(this, argu);
      output += "\tb "+lab+"\n";
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Reg()
    * f2 -> IntegerLiteral()
    * f3 -> Reg()
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String r1 = (String)n.f1.accept(this, argu);
      String off = (String)n.f2.accept(this, argu);
      String r2 = (String)n.f3.accept(this, argu);
      output += "\tsw "+r2+", "+off+"("+r1+")\n";
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Reg()
    * f2 -> Reg()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String r1 = (String)n.f1.accept(this, argu);
      String r2 = (String)n.f2.accept(this, argu);
      String off = (String)n.f3.accept(this, argu);
      output += "\tlw "+r1+", "+off+"("+r2+")\n";
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Reg()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String r = (String) n.f1.accept(this, argu);
      String e = "";
      if(n.f2.f0.choice instanceof HAllocate)
      { 
          e = (String)n.f2.accept(this, argu);
          output += "\tmove "+r+" $v0\n";
      }
      else if (n.f2.f0.choice instanceof BinOp)
      {
          String[] a = (String[])n.f2.accept(this, argu);
          output += a[0]+r+a[1];
      }
      else if (n.f2.f0.choice instanceof SimpleExp)
      {
          String se = (String)n.f2.accept(this, argu);
          NodeChoice expchoice = n.f2.f0;
          SimpleExp sep = (SimpleExp)expchoice.choice;
          NodeChoice sec = sep.f0;
          if(sec.choice instanceof Reg)
          {
            output += "\tmove "+r+" "+se+"\n";
          }
          else if(sec.choice instanceof Label)
          {
              output += "\tla "+r+" "+se+"\n";
          }
          else if(sec.choice instanceof IntegerLiteral)
          {
              output += "\tli "+r+" "+se+"\n";
          }
      }
      // String e = (String)n.f2.accept(this, argu);
      //assume li has less than 32k numbers
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public R visit(PrintStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String se = (String)n.f1.accept(this, argu);
      if(n.f1.f0.choice instanceof Reg)output += "\tmove $a0 "+se+"\n";
      else if(n.f1.f0.choice instanceof IntegerLiteral)output += "\tli $a0 "+se+"\n";
      output += "\tjal _print\n";
      return _ret;
   }

   /**
    * f0 -> "ALOAD"
    * f1 -> Reg()
    * f2 -> SpilledArg()
    */
   public R visit(ALoadStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String r = (String)n.f1.accept(this, argu);
      String off1 = (String)n.f2.accept(this, argu);
      off1 = String.valueOf(Integer.parseInt(off1)*4);
      // off = String.valueOf(Integer.parseInt(off)*4);
      int toff = Integer.parseInt(off1);
      String off = String.valueOf(findoff(toff));

      if(ga>0 &&na!=0&& poss(off))output += "\tlw "+r+", "+off+"($fp)\n";
      else if (ga>0 && na==0 &&poss(off1)) output +=  "\tlw "+r+", "+off+"($fp)\n";
      else output += "\tlw "+r+", "+off+"($sp)\n";
      // output += "\tlw "+r+", "+off+"($sp)\n";
      return _ret;
   }

   /**
    * f0 -> "ASTORE"
    * f1 -> SpilledArg()
    * f2 -> Reg()
    */
   public R visit(AStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String off1 = (String)n.f1.accept(this, argu);
      // off = String.valueOf(Integer.parseInt(off)*4);
      off1 = String.valueOf(Integer.parseInt(off1)*4);
      int toff = Integer.parseInt(off1);
      String  off = String.valueOf(findoff(toff));

      String r = (String)n.f2.accept(this, argu);
      if(ga>0 &&na!=0&& poss(off)) output += "\tsw "+r+", "+off+"($fp)\n";
      else if (ga>0 && na==0 &&poss(off1)) output +=  "\tsw "+r+", "+off+"($fp)\n";
      else  output += "\tsw "+r+", "+off+"($sp)\n";
      // output += "\tsw "+r+", "+off+"($sp)\n";
      return _ret;
   }

   /**
    * f0 -> "PASSARG"
    * f1 -> IntegerLiteral()
    * f2 -> Reg()
    */
   public R visit(PassArgStmt n, A argu) {
      R _ret=null;
      String off = (String)n.f1.accept(this, argu);
      off = String.valueOf((Integer.parseInt(off)-1)*4);
      String r = (String)n.f2.accept(this, argu);
      output += "\tsw "+r+", "+off+"($sp)\n";
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    */
   public R visit(CallStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String se = (String)n.f1.accept(this, argu);
      output += "\tjalr "+se+"\n";
      return _ret;
   }

   /**
    * f0 -> HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public R visit(Exp n, A argu) {
      R _ret=null;
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public R visit(HAllocate n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String se = (String)n.f1.accept(this, argu);
      output += "\tmove $a0 "+se+"\n";
      output += "\tjal _halloc\n";
      // output += "\tmove "+se+" $a0\n";
      return (R)(se);
   }

   /**
    * f0 -> Operator()
    * f1 -> Reg()
    * f2 -> SimpleExp()
    */
   public R visit(BinOp n, A argu) {
      R _ret=null;
      String op = (String)n.f0.accept(this, argu);
      String r = (String)n.f1.accept(this, argu);
      String se = (String)n.f2.accept(this, argu);
      // output += "\t"+op+" "+fr+" "+r+" "+se"\n";
      String[] a = new String[2];
      a[0] = "\t"+op+" ";
      a[1] = ", "+r+", "+se+"\n";
      return (R)a;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String op = (String)n.f0.choice.toString();
      if(op.equals("LE"))op = "sle";
      else if(op.equals("NE")) op = "sne";
      //assume some instrucntion
      else if(op.equals("PLUS")) op = "add";
      else if(op.equals("MINUS")) op = "sub";
      else if(op.equals("TIMES")) op = "mul";
      else if(op.equals("DIV")) op = "div";

      return (R)op;
   }

   /**
    * f0 -> "SPILLEDARG"
    * f1 -> IntegerLiteral()
    */
   public R visit(SpilledArg n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return n.f1.accept(this, argu);
   }

   /**
    * f0 -> Reg()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(SimpleExp n, A argu) {
      R _ret=null;
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "a0"
    *       | "a1"
    *       | "a2"
    *       | "a3"
    *       | "t0"
    *       | "t1"
    *       | "t2"
    *       | "t3"
    *       | "t4"
    *       | "t5"
    *       | "t6"
    *       | "t7"
    *       | "s0"
    *       | "s1"
    *       | "s2"
    *       | "s3"
    *       | "s4"
    *       | "s5"
    *       | "s6"
    *       | "s7"
    *       | "t8"
    *       | "t9"
    *       | "v0"
    *       | "v1"
    */
   public R visit(Reg n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return (R)("$"+n.f0.choice.toString());
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return (R)n.f0.toString();
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
       if(argu == null)
       {
           R _ret=null;
           n.f0.accept(this, argu);
           return (R)n.f0.toString();
      }
      else {
        String lab = (String)n.f0.toString();
        output += lab+":";
        return null;
      }
   }

   /**
    * f0 -> "//"
    * f1 -> SpillStatus()
    */
   public R visit(SpillInfo n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <SPILLED>
    *       | <NOTSPILLED>
    */
   public R visit(SpillStatus n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

}
